services:
  - type: web
    name: temtemsabah-admin
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: ADMIN_EMAIL
        value: antkkds@gmail.com
      - key: ADMIN_PASS
        value: Antkk@3626
