services:
  - type: web
    name: temtemsabah-admin
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_VERSION
        value: "18"
      - key: PORT
        value: "10000"
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASS
        sync: false
